name: stream_master
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  get: ^4.6.1
  image_picker: ^0.8.4+8
  video_compress: ^3.1.0
  video_player: ^2.2.18
  shared_preferences: ^2.0.13
  flutter_screenutil: ^5.3.1
  font_awesome_flutter: ^10.0.0
  flutter_app_minimizer: ^0.0.2
  flutter_svg: ^1.0.3
  share_plus: ^4.0.3
  intl: ^0.17.0
  cool_datepicker:
  favorite_button: ^0.0.4
  cached_network_image: ^3.0.0
  wechat_camera_picker: ^2.4.2
  wechat_assets_picker: ^5.5.8
  mime: ^1.0.1
  http_parser: ^4.0.0
  http: ^0.13.4
  fluttertoast: ^8.0.9
  camera: ^0.9.4+4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0
  flutter_launcher_icons_maker: ^0.10.2

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/logo.png"

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/

  # example:
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Bold.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
